---
# tasks file for haproxy
- name: Install packages
  apt:
    name: haproxy=1.8.8-1ubuntu0.9

- name: Set haproxy configs files
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    mode: '0644'
  notify: restart haproxy