---
# tasks file for ceph
- name: Install pip packages
  pip:
    name: "{{ pip_packages }}"

- name: Clone git repository
  git:
    repo: "{{ item.value }}"
    dest: "{{ repo_dir }}/{{ item.key }}"
    accept_hostkey: true
    force: true
  with_dict: "{{ git_repos_clone }}"

- name: Set crontab
  cron:
    name: "{{ item.key }}"
    minute: "{{ item.value.minute }}"
    hour: "{{ item.value.hour }}"
    job: "{{ item.value.command }}"
  with_dict: "{{ cron }}"
