---
# tasks file for common
- name: Create the "{{ repo_dir }}" directory if it does not exist
  file:
    path: "{{ repo_dir }}"
    state: directory
    mode: '0755'

- name: Install packages
  apt:
    name: "{{ packages }}"

- name: Put public keys to ssh config
  template:
    src: authorized_keys.j2
    dest: /root/.ssh/authorized_keys
    mode: '0644'

- name: configure sshd
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^{{ item.key }}"
    line: "{{ item.key }} {{ item.value }}"
    state: present
    owner: root
    group: root
    mode: 0600
    backup: yes
  with_dict: "{{ sshd_config }}"
  notify: restart sshd

- name: Allow ssh to certain port only
  ufw:
    rule: allow
    port: 2200
  notify: restart ufw

- name: Set firewall default policy
  ufw:
    state: enabled
    policy: reject

- name: Configure ufw firewall
  ufw:
    rule: allow
    src: '{{ item }}'
  with_items: "{{ groups['all'] }}"
  notify: restart ufw





