---
- name: Create folders
  file:
    path: "/mnt/{{ item }}"
    state: directory
    mode: '0755'
  with_items: "{{ glusterfs_mount_dir }}"

- name: Ensure the Gluster volume is mounted.
  mount:
    path: "/mnt/{{ glusterfs_mount_dir }}"
    src: "{{ groups.dbservers[0] }}:/{{ glusterfs_mount_dir  }}"
    fstype: glusterfs
    opts: "defaults,_netdev"
    state: mounted