---
- name: Join another master to Kubernetes cluster
  shell: |
    kubeadm join {{ kubeadm_config.controlPlaneEndpoint }} \
                 --token {{ hostvars[groups['k8s_master'][0]]['K8S_TOKEN'].stdout }} \
                 --discovery-token-ca-cert-hash sha256:{{ hostvars[groups['k8s_master'][0]]['K8S_MASTER_CA_HASH'].stdout }} \
                 --certificate-key {{ hostvars[groups['k8s_master'][0]]['K8S_MASTER_CA_SECRET'].stdout }} \
                 --control-plane
  register: join_cluster

- name: Ensure dir $HOME/.kube exists
  file:
    path: "/root/{{ admin_dir }}"
    state: directory
    follow: true

- name: Copy admin file
  copy:
    remote_src: yes
    src: "{{ admin_file_src }}"
    dest: "/root/{{ admin_dir }}/{{ admin_file_dst }}"

- name: Output the k8s cluster joining
  debug: var=join_cluster
