---
# tasks file for docker
- name: Add an Apt signing key of the repository
  apt_key:
    url: "{{ docker.apt_key_url }}"
    state: present

- name: Install docker repositories
  apt_repository:
    repo: "{{ docker.apt_repo }}"
    state: present

- name: Update apt packages
  become: true
  apt:
    upgrade: no
    update_cache: yes

- name: Install docker
  apt:
    name: "{{ docker.packages }}"